/**
 * Generates scripts/backfill-contact-tags.sql from scripts/brand-directory.csv.
 *
 *   npx tsx scripts/backfill-contact-tags.ts       (or: node --experimental-strip-types)
 *
 * A one-time sweep over contacts that already exist, NOT an import: every
 * statement it emits is an UPDATE keyed on a company name, so a brand in the
 * directory that nobody has a contact for stays out of the contact book. The
 * generated .sql is committed alongside this file, the same way
 * scripts/seed-cold-email-templates.sql is, so the exact statements that ran
 * against production are reviewable without re-running anything.
 *
 * Matching is exact on lower(trim(company)) = lower(trim(brand)). No fuzzy
 * matching: "Heyday Canning Co." and "Heyday Canning" are a judgement call
 * about whether two records are the same company, and a backfill that guesses
 * wrong writes a wrong category onto a real contact silently.
 *
 * Seven brand names appear twice in the directory with different revenue
 * figures (an upstream dedupe artifact). First occurrence wins, which is
 * arbitrary but stable — re-running this file produces byte-identical SQL.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const HERE = new URL(".", import.meta.url).pathname;
const CSV = join(HERE, "brand-directory.csv");
const OUT = join(HERE, "backfill-contact-tags.sql");

/**
 * Minimal RFC 4180 reader. The directory quotes any field containing a comma
 * (most of the long ARR notes do) and escapes a literal quote by doubling it,
 * so splitting on "," would shear those rows in half.
 */
function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let quoted = false;
  // Strip a UTF-8 BOM and normalise CRLF so a Windows-saved export parses the
  // same as a Unix one.
  const src = text.replace(/^﻿/, "").replace(/\r\n?/g, "\n");

  for (let i = 0; i < src.length; i++) {
    const c = src[i];
    if (quoted) {
      if (c === '"') {
        if (src[i + 1] === '"') { field += '"'; i++; } else { quoted = false; }
      } else field += c;
      continue;
    }
    if (c === '"') quoted = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
    else field += c;
  }
  if (field !== "" || row.length) { row.push(field); rows.push(row); }
  return rows;
}

/** SQL string literal. Doubling the quote is the whole of SQLite's escaping. */
const q = (s: string) => "'" + s.replace(/'/g, "''") + "'";

const rows = parseCsv(readFileSync(CSV, "utf8"));
const header = rows.shift();
if (!header || header[0] !== "brand") {
  throw new Error(`unexpected header: ${JSON.stringify(header)}`);
}
const col = {
  brand: header.indexOf("brand"),
  category: header.indexOf("category"),
  arr: header.indexOf("ARR"),
};
for (const [name, idx] of Object.entries(col)) {
  if (idx < 0) throw new Error(`missing column: ${name}`);
}

// First occurrence wins, keyed the same way the UPDATE matches.
const byBrand = new Map<string, { brand: string; category: string; arr: string }>();
let duplicates = 0;
for (const r of rows) {
  const brand = (r[col.brand] ?? "").trim();
  if (!brand) continue;
  const key = brand.toLowerCase();
  if (byBrand.has(key)) { duplicates++; continue; }
  byBrand.set(key, {
    brand,
    category: (r[col.category] ?? "").trim(),
    arr: (r[col.arr] ?? "").trim(),
  });
}

// `founded` is read and dropped on purpose: it is in the directory, it is not
// on the contact, and silently ignoring a column reads as an oversight.
const LIMITS = { category: 200, arr: 1_000 };
const out: string[] = [];
out.push(`-- Backfill: brand category and ARR onto contacts that already exist.
--
-- GENERATED by scripts/backfill-contact-tags.ts from scripts/brand-directory.csv.
-- Edit those, re-run the generator; do not hand-edit this file.
--
-- Not a migration. migrations/ is schema, replayed into every new database
-- through Wrangler's d1_migrations ledger; this is a one-time data sweep
-- against one contact book, and replaying it elsewhere would mean writing 2024
-- revenue estimates onto whatever companies happened to share a name. The
-- column definitions live in migrations/0016_contact_category_arr.sql.
--
--   npx wrangler d1 execute crm-db --local  --file=scripts/backfill-contact-tags.sql
--   npx wrangler d1 execute crm-db --remote --file=scripts/backfill-contact-tags.sql
--
-- Every statement is an UPDATE. Nothing here inserts a contact: a brand the
-- directory knows about but nobody is working is not a lead, and the contact
-- book is a record of who someone chose to add.
--
-- Matching is exact on lower(trim(company)), so a brand with no contact updates
-- zero rows and a contact with no brand keeps NULL in both columns. That is the
-- common case, not an error — roughly a third of the book is influencer handles
-- and test rows that no directory entry describes.
--
-- Re-running is harmless: each statement sets both columns to the same literal
-- values, so this is idempotent by construction rather than by guard.
--
-- ${byBrand.size} brands (${duplicates} duplicate brand names dropped, first occurrence kept).
`);

for (const { brand, category, arr } of byBrand.values()) {
  if (category.length > LIMITS.category) throw new Error(`category too long: ${brand}`);
  if (arr.length > LIMITS.arr) throw new Error(`arr too long: ${brand} (${arr.length})`);
  out.push(
    `UPDATE contacts SET category = ${q(category)}, arr = ${q(arr)}\n` +
    ` WHERE lower(trim(company)) = ${q(brand.toLowerCase())};`,
  );
}

writeFileSync(OUT, out.join("\n") + "\n");
console.error(
  `${byBrand.size} brands -> ${OUT} (${duplicates} duplicates dropped, ` +
  `${[...byBrand.values()].filter((b) => b.arr.length <= 60).length} figure-shaped ARR values)`,
);
